import Head from "next/head";
import Image from "next/image";
import MainLayout from "@/components/layout/MainLayout";
import {Button} from "@mantine/core";
import MainHero from "@/components/modules/MainHero.jsx/MainHero";

function Home() {
	return (
		<>
			<Head>
				<title>SkyLang</title>
				<meta name="description" content="Generated by create next app"/>
				<meta name="viewport" content="width=device-width, initial-scale=1"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>
			<main className={``}>
				{/*<h1>Test</h1>*/}
				{/*<Button>Test</Button>*/}
				<MainHero/>
			</main>
		</>
	);
}

Home.getLayout = (page) => (
	<MainLayout>
		{page}
	</MainLayout>
)

export default Home
